// <auto-generated />
using System;
using Fairhr.Service.A;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fairhr.Service.A.Migrations
{
    [DbContext(typeof(OrderInfoContext))]
    [Migration("20190924084103_update")]
    partial class update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Fairhr.Service.A.OrderInfo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32);

                    b.Property<DateTime>("CraeteTime");

                    b.Property<string>("Money")
                        .HasMaxLength(32);

                    b.Property<string>("Name")
                        .HasMaxLength(64);

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<int>("stauts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(2)")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("OrderInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
